#!/bin/sh

# Debian postinst script for Kannel.

set -e

# Create a "kannel" user. This has modeled after the code in the postfix.deb
# postinst. We first try to set the ownership of /var/log/kannel. If that
# fails, we create the user and re-try. If that still fails, we abort.

if chown kannel:root /var/log/kannel 2>/dev/null
then
    :
elif adduser --system --no-create-home --group kannel
then
    chown kannel:root /var/log/kannel
else
    echo "Cannot create user kannel and/or group kannel." 1>&2
    echo "Must have those before kannel can be installed." 1>&2
    echo "Sorry." 1>&2
    exit 1
fi

# /var/log/kannel contains potentially sensitive information, such as
# people's SMS messages. It must not be readable by the world.

chmod 0700 /var/log/kannel

# Set the ownership of /etc/kannel as well. The Kannel config files often
# contain passwords, so they should not be readable. The permissions in
# the .deb are already set to 0700, but set them to that just in case
# someone is upgrading from an old version with different permissions.

chown kannel.root /etc/kannel
chmod 0700 /etc/kannel

# Create /var/run/kannel for Kannel pid files, which are created by
# user kannel, not user root.

mkdir -p /var/run/kannel
chown kannel.root /var/run/kannel

# Start Kannel.
# XXX we *should* check that which run-level we're in and only start
# Kannel if /etc/rcX.d/S??kannel exists. I don't know how to figure out
# the current run-level, though.
# XXX Oops, filerc means that we means that we can't check the link.
# XXX Current run level can be received via runlevel(8).

/etc/init.d/kannel start


#DEBHELPER#
